version: "3.7"

services:
  pyspark:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    volumes:
      - ./data:/home/jovyan/work
    ports:
      - "9999:8888"
 